<a href="https://colab.research.google.com/github/Danicoder/Especializacion_IA_BigData/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
##Subiendo el Archivo
from google.colab import files
load=files.upload()

Saving titanic_train.csv to titanic_train.csv

In [30]:
print("**********************EJERCICIO 1**********************")
import pandas as pd
##LECTURA DEL ARCHIVO
df = pd.read_csv('titanic_train.csv')
print(df)
print("**********************EJERCICIO 2**********************")
#Imprimir 20 primeras filas
print(df.head(20))
print("**********************EJERCICIO 3**********************")
#Imprimir las últimas 5 filas
print(df.tail(5))
print("**********************EJERCICIO 4**********************")
#Imprime la información del fichero para saber el tipo de dato
print(df.info())
print("**********************EJERCICIO 5**********************")
#Imprime el número de filas y columnas
print(f"número de filas y columnas: {df.shape}")
print("**********************EJERCICIO 6**********************")
#Imprime resumen estadístico
print(df.describe())
print("**********************EJERCICIO 7**********************")
titanic= pd.read_csv("titanic_train.csv")
print(titanic.describe())
#Imprimir datos con pasajeros > 30 años
pasajeros_mayor_30 = titanic[titanic['Age']>30].describe()
print(f" Pasajeros mayores de 30 años: {pasajeros_mayor_30}")
quince_primeros = pasajeros_mayor_30.head(15)
print(f" 15 primeros de la lista anterior: {quince_primeros}")
#Imprimir pasajeros con edad comprendida entre 45 y 55 años
pasajeros_entre_45_55= titanic[(titanic['Age']>=45) & (titanic['Age']<=55)].describe()
print(f" pasajeros con edad comprendida entre 45 y 55 años: {pasajeros_entre_45_55}")

#Para saber la cantidad de pasajeros que cumplen la condición
print("**********************EJERCICIO 8**********************")
cantidad = pasajeros_entre_45_55['PassengerId'].count()
print(f"Cantidad de pasajeros: {cantidad}")

#Pasajeros que viajan solos
print("**********************EJERCICIO 9**********************")
pasajeros_singles= titanic[titanic['SibSp']==0].shape[0]
print(f"Pasajeros que viajan solos: {pasajeros_singles}") #shape[0] --> solo devuelve nº filas

#Filas de pasajeros que sobrevivieron
print("**********************EJERCICIO 10**********************")
sobreviviventes = titanic.loc[titanic["Survived"] == 1].shape[0]
print(f"pasajeros que sobrevivieron: {sobreviviventes}")

#filas de hombres que sobrevivieron
print("**********************EJERCICIO 11**********************")
sobreviviventes_h = titanic.loc[(titanic["Survived"] == 1) & (titanic["Sex"] == "male")].shape[0]
print(f"Hombres que sobrevivieron: {sobreviviventes_h}")

#Número de columnas y filas
print("**********************EJERCICIO 12**********************")
num_col_row = titanic[["Age","Sex"]].shape
print(f"Número de columnas y filas: {num_col_row}")

#Pasajeros con cabina 2 y 3
print("**********************EJERCICIO 13**********************")
pasajeros_cabina_2_3 = titanic[(titanic['Pclass']==2) | (titanic['Pclass']==3)].head()
print(f"Pasajeros con cabina 2 y 3: {pasajeros_cabina_2_3}")

#Pasajeros con edad != 0
print("**********************EJERCICIO 14**********************")
pasajeros_edad_notnull =titanic[titanic['Age'].notna()].describe()
print(f"Pasajeros con edad != 0: {pasajeros_edad_notnull}")
pasajeros_edad_notnull.shape

#Pasajeros entre las filas 15 - 30 y columnas 4-7
print("**********************EJERCICIO 15**********************")
pasajeros_filas_col= titanic.iloc[14:30,3:7]
print(f"Pasajeros entre las filas 15 - 30 y columnas 4-7: {pasajeros_filas_col}")

#Filas compredidas entre 15 - 30 y columnas entre 1-4
print("**********************EJERCICIO 16**********************")
pasajeros_filas_col2= titanic.iloc[14:30,0:4]
print(f"Filas compredidas entre 15 - 30 y columnas entre 1-4: {pasajeros_filas_col2}")

#Edad pasajeros Titanic (20 primeros)
print("**********************EJERCICIO 17**********************")
edad = titanic["Age"]
print(f"Edad pasajeros Titanic (20 primeros): {edad.head(20)}")

#Calcula la edad media de los pasajeros del Titanic
print("**********************EJERCICIO 18**********************")
edad_media=titanic["Age"].mean()
print(f"Edad media de los pasajeros del Titanic{edad_media}")

#Valor medio de edad y precio del billete de los pasajeros
print("**********************EJERCICIO 19**********************")
media_edad = titanic["Age"].mean()
precio_medio = titanic['Fare'].mean()
print(f'Edad media: {edad_media}')
print(f'Precio medio del billete: {precio_medio}')

#valor medio, promedio mínimo, máximo, percentiles de la Edad y el precio del billete
print("**********************EJERCICIO 20**********************")
edad_media = titanic['Age'].mean()
edad_minima = titanic['Age'].min()
edad_maxima = titanic['Age'].max()
suma_edades = edad_media + edad_minima + edad_maxima
promedio = suma_edades/3
percentiles_edad = titanic['Age'].quantile([0.25,0.75])  # 25%, 75%
print(f'Valor medio: {edad_media}, mínimo: {edad_minima} y máximo es: {edad_maxima}')
print(f'El promedio es: {promedio}')
print(f'Percentiles de la Edad:\n{percentiles_edad}')


precio_media = titanic['Fare'].mean()
precio_minima = titanic['Fare'].min()
precio_maxima = titanic['Fare'].max()
suma_precios = precio_media + precio_minima + precio_maxima
promedio = suma_precios / 3
percentiles_edad = titanic['Fare'].quantile([0.25,0.75])  # 25%, 75%

print(f'Valor medio: {precio_media}, mínimo: {precio_minima} y máximo es: {precio_maxima}')
print(f'El promedio del precio es: {promedio}')
print(f'Percentiles del precio:\n{percentiles_edad}')

#Calcular la media de supervivientes del barco.
print("**********************EJERCICIO 21**********************")
media_superviviente = titanic['Survived'].mean()
print(f"Media de supervivientes: {media_superviviente}")

#Calcular el valor medio, promedio, mínimo, máximo y percentiles de los supervivientes.
print("**********************EJERCICIO 22**********************")
supervivientes_media = titanic['Survived'].mean()
supervivientes_minima = titanic['Survived'].min()
supervivientes_maxima = titanic['Survived'].max()
suma_supervivientes = precio_media + precio_minima + precio_maxima
promedio = suma_supervivientes / 3
percentiles_supervivientes = titanic['Survived'].quantile([0.25,0.75])  # 25%, 75%

print(f'Valor medio: {supervivientes_media}, mínimo: {supervivientes_minima} y máximo es: {supervivientes_maxima}')
print(f'El promedio de los supervivientes es: {promedio}')
print(f'Percentiles de los supervivientes es:\n{percentiles_supervivientes}')

#Muestra la edad media agrupadas por el sexo (de esta forma sabremos la media de los hombres y mujeres).
print("**********************EJERCICIO 23**********************")
edad_media = titanic[['Sex','Age']].groupby("Sex").mean()
print(f"La media de los hombres y de las mujeres es de: {edad_media} ")
#Aplica el groupby por sexo pero para todas las columnas
print("**********************EJERCICIO 24**********************")
agrupar = titanic.groupby('Sex').mean(numeric_only=True)
print(f"Agrupando por sexo: \n {agrupar}")
#Precio medio de la tarifa de la entrada para cada una de las combinaciones de sexo y clase de cabina
print("**********************EJERCICIO 25**********************")
precio_medio = titanic.groupby(["Sex", "Pclass"])["Fare"].mean()
print(f"Precio medio de la tarifa de la entrada: {precio_medio}")
#Número de pasajero en cada una de las clases de cabina (Pclass)
print("**********************EJERCICIO 26**********************")
c_pasajeros = titanic['Pclass'].value_counts()
print(f"Número de pasajeros en cada cabina: {c_pasajeros}")

#número de pasajeros en cada una de las clases de cabina
print("**********************EJERCICIO 27**********************")
n_pasajeros = titanic.groupby("Pclass").size()
total_pasajeros = titanic.groupby("Pclass").count()
print(f"Número pasajeros por cabina: {n_pasajeros}")
print(f"Total pasajeros por cabina: {total_pasajeros}")

#Calcula el número de cabinas (Cabin)
print("**********************EJERCICIO 28**********************")
frecuencia_cabina = titanic.groupby(["Pclass","Cabin"])["Survived"].value_counts()
entradas_cabina_NONULL = titanic.groupby(["Pclass","Cabin"])["Survived"].count()
total_cabina = titanic.groupby(["Pclass","Cabin"])["Survived"].size()
print(f"Frecuencia de cabinas: {frecuencia_cabina}")
print(f"Entradas de cabinas (no nulas): {entradas_cabina_NONULL}")
print(f"Total de cabinas: {total_cabina}")

#Ordena los datos del Titanic según la edad de los pasajeros
print("**********************EJERCICIO 29**********************")
titanic_ordenado = titanic.sort_values(by='Age').head(15)
print(titanic_ordenado)

#Ordena los datos del Titanic según la edad de los pasajeros
print("**********************EJERCICIO 30**********************")
titanic_ordenado_descendente = titanic.sort_values(by='Age').tail(15)
print(titanic_ordenado_descendente)

**********************EJERCICIO 1**********************
     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
**********************EJERCICIO 2**********************
    PassengerId  Survived  Pclass  \
0             1         0       3
1             2         1       1
2             3         1       3
3             4         1       1
4             5         0       3
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3
11           12         1       1
12           13         0       3
13           14         0       3
14           15         0       3
15           16         1       2
16           17         0       3
17           18         1       2
18           19         0       3
19           20         1       3

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss. Laina  female  26.0      0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
5                                    Moran, Mr. James    male   NaN      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master. Gosta Leonard    male   2.0      3
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1
11                           Bonnell, Miss. Elizabeth  female  58.0      0
12                     Saundercock, Mr. William Henry    male  20.0      0
13                        Andersson, Mr. Anders Johan    male  39.0      1
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0
16                               Rice, Master. Eugene    male   2.0      4
17                       Williams, Mr. Charles Eugene    male   NaN      0
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1
19                            Masselmani, Mrs. Fatima  female   NaN      0

    Parch            Ticket     Fare Cabin Embarked
0       0         A/5 21171   7.2500   NaN        S
1       0          PC 17599  71.2833   C85        C
2       0  STON/O2. 3101282   7.9250   NaN        S
3       0            113803  53.1000  C123        S
4       0            373450   8.0500   NaN        S
5       0            330877   8.4583   NaN        Q
6       0             17463  51.8625   E46        S
7       1            349909  21.0750   NaN        S
8       2            347742  11.1333   NaN        S
9       0            237736  30.0708   NaN        C
10      1           PP 9549  16.7000    G6        S
11      0            113783  26.5500  C103        S
12      0         A/5. 2151   8.0500   NaN        S
13      5            347082  31.2750   NaN        S
14      0            350406   7.8542   NaN        S
15      0            248706  16.0000   NaN        S
16      1            382652  29.1250   NaN        Q
17      0            244373  13.0000   NaN        S
18      0            345763  18.0000   NaN        S
19      0              2649   7.2250   NaN        C
**********************EJERCICIO 3**********************
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q
**********************EJERCICIO 4**********************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
**********************EJERCICIO 5**********************
número de filas y columnas: (891, 12)
**********************EJERCICIO 6**********************
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200
**********************EJERCICIO 7**********************
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200
 Pasajeros mayores de 30 años:        PassengerId    Survived      Pclass         Age       SibSp  \
count   305.000000  305.000000  305.000000  305.000000  305.000000
mean    467.659016    0.406557    1.927869   42.927869    0.347541
std     252.381333    0.491998    0.863006   10.060412    0.535456
min       2.000000    0.000000    1.000000   30.500000    0.000000
25%     253.000000    0.000000    1.000000   35.000000    0.000000
50%     487.000000    0.000000    2.000000   40.000000    0.000000
75%     674.000000    1.000000    3.000000   49.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    3.000000

            Parch        Fare
count  305.000000  305.000000
mean     0.383607   42.352910
std      0.949581   63.337041
min      0.000000    0.000000
25%      0.000000    9.587500
50%      0.000000   26.000000
75%      0.000000   52.000000
max      6.000000  512.329200
 15 primeros de la lista anterior:        PassengerId    Survived      Pclass         Age       SibSp  \
count   305.000000  305.000000  305.000000  305.000000  305.000000
mean    467.659016    0.406557    1.927869   42.927869    0.347541
std     252.381333    0.491998    0.863006   10.060412    0.535456
min       2.000000    0.000000    1.000000   30.500000    0.000000
25%     253.000000    0.000000    1.000000   35.000000    0.000000
50%     487.000000    0.000000    2.000000   40.000000    0.000000
75%     674.000000    1.000000    3.000000   49.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    3.000000

            Parch        Fare
count  305.000000  305.000000
mean     0.383607   42.352910
std      0.949581   63.337041
min      0.000000    0.000000
25%      0.000000    9.587500
50%      0.000000   26.000000
75%      0.000000   52.000000
max      6.000000  512.329200
 pasajeros con edad comprendida entre 45 y 55 años:        PassengerId   Survived     Pclass        Age     SibSp      Parch  \
count    75.000000  75.000000  75.000000  75.000000  75.00000  75.000000
mean    475.466667   0.413333   1.666667  49.093333   0.40000   0.306667
std     243.945183   0.495748   0.810961   3.004156   0.54525   0.752892
min       7.000000   0.000000   1.000000  45.000000   0.00000   0.000000
25%     270.000000   0.000000   1.000000  47.000000   0.00000   0.000000
50%     493.000000   0.000000   1.000000  49.000000   0.00000   0.000000
75%     679.500000   1.000000   2.000000  51.000000   1.00000   0.000000
max     874.000000   1.000000   3.000000  55.000000   2.00000   4.000000

             Fare
count   75.000000
mean    42.622449
std     40.907744
min      0.000000
25%     13.500000
50%     26.550000
75%     60.287500
max    247.520800
**********************EJERCICIO 8**********************
Cantidad de pasajeros: 8
**********************EJERCICIO 9**********************
Pasajeros que viajan solos: 608
**********************EJERCICIO 10**********************
pasajeros que sobrevivieron: 342
**********************EJERCICIO 11**********************
Hombres que sobrevivieron: 109
**********************EJERCICIO 12**********************
Número de columnas y filas: (891, 2)
**********************EJERCICIO 13**********************
Pasajeros con cabina 2 y 3:    PassengerId  Survived  Pclass                            Name     Sex  \
0            1         0       3         Braund, Mr. Owen Harris    male
2            3         1       3          Heikkinen, Miss. Laina  female
4            5         0       3        Allen, Mr. William Henry    male
5            6         0       3                Moran, Mr. James    male
7            8         0       3  Palsson, Master. Gosta Leonard    male

    Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0  22.0      1      0         A/5 21171   7.2500   NaN        S
2  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
4  35.0      0      0            373450   8.0500   NaN        S
5   NaN      0      0            330877   8.4583   NaN        Q
7   2.0      3      1            349909  21.0750   NaN        S
**********************EJERCICIO 14**********************
Pasajeros con edad != 0:        PassengerId    Survived      Pclass         Age       SibSp  \
count   714.000000  714.000000  714.000000  714.000000  714.000000
mean    448.582633    0.406162    2.236695   29.699118    0.512605
std     259.119524    0.491460    0.838250   14.526497    0.929783
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     222.250000    0.000000    1.000000   20.125000    0.000000
50%     445.000000    0.000000    2.000000   28.000000    0.000000
75%     677.750000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    5.000000

            Parch        Fare
count  714.000000  714.000000
mean     0.431373   34.694514
std      0.853289   52.918930
min      0.000000    0.000000
25%      0.000000    8.050000
50%      0.000000   15.741700
75%      1.000000   33.375000
max      6.000000  512.329200
**********************EJERCICIO 15**********************
Pasajeros entre las filas 15 - 30 y columnas 4-7:                                                  Name     Sex   Age  SibSp
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0
16                               Rice, Master. Eugene    male   2.0      4
17                       Williams, Mr. Charles Eugene    male   NaN      0
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1
19                            Masselmani, Mrs. Fatima  female   NaN      0
20                               Fynney, Mr. Joseph J    male  35.0      0
21                              Beesley, Mr. Lawrence    male  34.0      0
22                        McGowan, Miss. Anna "Annie"  female  15.0      0
23                       Sloper, Mr. William Thompson    male  28.0      0
24                      Palsson, Miss. Torborg Danira  female   8.0      3
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1
26                            Emir, Mr. Farred Chehab    male   NaN      0
27                     Fortune, Mr. Charles Alexander    male  19.0      3
28                      O'Dwyer, Miss. Ellen "Nellie"  female   NaN      0
29                                Todoroff, Mr. Lalio    male   NaN      0
**********************EJERCICIO 16**********************
Filas compredidas entre 15 - 30 y columnas entre 1-4:     PassengerId  Survived  Pclass  \
14           15         0       3
15           16         1       2
16           17         0       3
17           18         1       2
18           19         0       3
19           20         1       3
20           21         0       2
21           22         1       2
22           23         1       3
23           24         1       1
24           25         0       3
25           26         1       3
26           27         0       3
27           28         0       1
28           29         1       3
29           30         0       3

                                                 Name
14               Vestrom, Miss. Hulda Amanda Adolfina
15                   Hewlett, Mrs. (Mary D Kingcome)
16                               Rice, Master. Eugene
17                       Williams, Mr. Charles Eugene
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...
19                            Masselmani, Mrs. Fatima
20                               Fynney, Mr. Joseph J
21                              Beesley, Mr. Lawrence
22                        McGowan, Miss. Anna "Annie"
23                       Sloper, Mr. William Thompson
24                      Palsson, Miss. Torborg Danira
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
26                            Emir, Mr. Farred Chehab
27                     Fortune, Mr. Charles Alexander
28                      O'Dwyer, Miss. Ellen "Nellie"
29                                Todoroff, Mr. Lalio
**********************EJERCICIO 17**********************
Edad pasajeros Titanic (20 primeros): 0     22.0
1     38.0
2     26.0
3     35.0
4     35.0
5      NaN
6     54.0
7      2.0
8     27.0
9     14.0
10     4.0
11    58.0
12    20.0
13    39.0
14    14.0
15    55.0
16     2.0
17     NaN
18    31.0
19     NaN
Name: Age, dtype: float64
**********************EJERCICIO 18**********************
Edad media de los pasajeros del Titanic29.69911764705882
**********************EJERCICIO 19**********************
Edad media: 29.69911764705882
Precio medio del billete: 32.204207968574636
**********************EJERCICIO 20**********************
Valor medio: 29.69911764705882, mínimo: 0.42 y máximo es: 80.0
El promedio es: 36.70637254901961
Percentiles de la Edad:
0.25    20.125
0.75    38.000
Name: Age, dtype: float64
Valor medio: 32.204207968574636, mínimo: 0.0 y máximo es: 512.3292
El promedio del precio es: 181.5111359895249
Percentiles del precio:
0.25     7.9104
0.75    31.0000
Name: Fare, dtype: float64
**********************EJERCICIO 21**********************
Media de supervivientes: 0.3838383838383838
**********************EJERCICIO 22**********************
Valor medio: 0.3838383838383838, mínimo: 0 y máximo es: 1
El promedio de los supervivientes es: 181.5111359895249
Percentiles de los supervivientes es:
0.25    0.0
0.75    1.0
Name: Survived, dtype: float64
**********************EJERCICIO 23**********************
La media de los hombres y de las mujeres es de:               Age
Sex
female  27.915709
male    30.726645
**********************EJERCICIO 24**********************
Agrupando por sexo:
         PassengerId  Survived    Pclass        Age     SibSp     Parch  \
Sex
female   431.028662  0.742038  2.159236  27.915709  0.694268  0.649682
male     454.147314  0.188908  2.389948  30.726645  0.429809  0.235702

             Fare
Sex
female  44.479818
male    25.523893
**********************EJERCICIO 25**********************
Precio medio de la tarifa de la entrada: Sex     Pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: Fare, dtype: float64
**********************EJERCICIO 26**********************
Número de pasajeros en cada cabina: Pclass
3    491
1    216
2    184
Name: count, dtype: int64
**********************EJERCICIO 27**********************
Número pasajeros por cabina: Pclass
1    216
2    184
3    491
dtype: int64
Total pasajeros por cabina:         PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass
1               216       216   216  216  186    216    216     216   216
2               184       184   184  184  173    184    184     184   184

1.   ¿Cuántos pasajeros mayores de 30 años te salen? 305
2.   Como sacarías los 15 primeros de la lista anterior: df.tail(15)
3.   ¿Cuántos pasajeros tienen entre 45 y 55 años? 35.660 pasajeros
4.   ¿Cuántos pasajeros viajan solos? 276.865
5.   ¿Cúantos filas de pasajeros sobrevivieron? 342
6.   ¿Cúantos filas de pasajeros hombres sobrevivivieron? 109
7.   Elemento de lista



Total pasajeron: 397.386